name: "process_datasets"
namespace: "denoising/workflows"
argument_groups:
  - name: Inputs
    arguments:
      - name: "--input"
        required: true
        example: dataset.h5ad
        __merge__: "/src/api/file_common_dataset.yaml"
  - name: Outputs
    arguments:
      - name: "--output_train"
        __merge__: "/src/api/file_train_h5ad.yaml"
        direction: output
        required: true
      - name: "--output_test"
        __merge__: "/src/api/file_test_h5ad.yaml"
        direction: output
        required: true
resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf
  - path: /common/nextflow_helpers/helper.nf
dependencies:
  - name: common/check_dataset_schema
    repository:
      type: github
      repo: openproblems-bio/openproblems-v2
  - name: denoising/process_dataset
runners:
  - type: nextflow
