name: "process_datasets"
namespace: "workflows"
argument_groups:
  - name: Inputs
    arguments:
      - name: "--input"
        required: true
        example: dataset.h5ad
        __merge__: "/src/api/file_common_dataset.yaml"
  - name: Outputs
    arguments:
      - name: "--output_train"
        __merge__: "/src/api/file_train.yaml"
        direction: output
        required: true
      - name: "--output_test"
        __merge__: "/src/api/file_test.yaml"
        direction: output
        required: true
resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf
  - path: /common/nextflow_helpers/helper.nf
dependencies:
  - name: common/check_dataset_schema
    repository: openproblems
  - name: data_processors/process_dataset
runners:
  - type: nextflow
